package com.dw.ngms.cis.service.event;

/**
 * @author : prateekgoel
 * @since : 20/11/20, Fri
 **/
public enum EventType {

    USER_REGISTRATION("USER_REGISTRATION"),
    INTERNAL_USER_REGISTRATION("INTERNAL_USER_REGISTRATION"),
    USER_PROFILE_UPDATE("USER_PROFILE_UPDATE"),
    USER_PASSWORD_RESET("USER_PASSWORD_RESET"),
    USER_LOGGED_IN_SUCCESSFULLY("USER_LOGGED_IN_SUCCESSFULLY"),
    USER_CHANGED_EMAIL("USER_CHANGED_EMAIL"),
    USER_ACTIVATE("USER_ACTIVATE"),
    USER_DEACTIVATE("USER_DEACTIVATE"),
    USER_FORGOT_PASSWORD("USER_FORGOT_PASSWORD"),
    USER_APPROVED("USER_APPROVED"),
    USER_REJECTED("USER_REJECTED"),
    USER_LOCKED("USER_LOCKED"),
    PREPACKAGE_SUBSCRIPTION_NOTIFICATION("PREPACKAGE_SUBSCRIPTION_NOTIFICATION"),
    PREPACKAGE_SUBSCRIPTION_EXECUTION("PREPACKAGE_SUBSCRIPTION_EXECUTION"),
    DISPATCH("DISPATCH"),
    DATA_VIEWER_REQUEST("DATA_VIEWER_REQUEST"),
    DATA_VIEWER_REQUEST_PROCESSED("DATA_VIEWER_REQUEST_PROCESSED"),
    WORKFLOW_NOTIFICATIONS("WORKFLOW_NOTIFICATIONS"),
    ASSISTANT_APPROVED_PLS("ASSISTANT_APPROVED"),
    ASSISTANT_REJECTED_PLS("ASSISTANT_REJECTED"),
    ASSISTANT_UNLINKED_PLS("ASSISTANT_UNLINKED"),
    USER_REGISTRATION_PENDING("USER_REGISTRATION_PENDING");

    private final String message;

    EventType(String message) {
        this.message = message;
    }
}
